### ISSUE TITLE
url中多了个空格

### ISSUE THREAD

**Issue by YaozhongZhang** [yzyyz1387/hamSoftware#1]
https://github.com/yzyyz1387/hamSoftware/blob/ef8d419b12bab2f9550273f9a452d94979a479da/res-pc.json#L68

改为
```
 "url": "https://sourceforge.net/projects/wsjt/", 
```

**Comment by yzyyz1387** [comment]
fixed at https://github.com/yzyyz1387/hamSoftware/commit/fd1cc645bb737f6d2cbaae8405ad8ab13775bef9
